Repository microsoft/mu_feature_ipmi, pull requests merged in 2023-06, with the labels that each got.

#123 Create SpmiTable DXE Driver to initialize SPMI table and install it by AcpiTableProtocol
  IpmiFeaturePkg/IpmiFeaturePkg.ci.yaml
  IpmiFeaturePkg/IpmiFeaturePkg.dec
  IpmiFeaturePkg/IpmiFeaturePkg.dsc
  IpmiFeaturePkg/SpmiTable/GoogleTest/SpmiTableGoogleTest.cpp
  IpmiFeaturePkg/SpmiTable/GoogleTest/SpmiTableGoogleTest.inf
  IpmiFeaturePkg/SpmiTable/Readme.md
  IpmiFeaturePkg/SpmiTable/SpmiTable.c
  IpmiFeaturePkg/SpmiTable/SpmiTable.inf
  IpmiFeaturePkg/Test/IpmiFeaturePkgHostTest.dsc
Labels: type:documentation, impact:testing

#138 ci.yaml: add PrEval entry
  IpmiFeaturePkg/IpmiFeaturePkg.ci.yaml
Labels: impact:non-functional

#140 202302 introduced IpmiCommandLib.h as part of the MdeModulePkg.
  .pytool/CISettings.py
  IpmiFeaturePkg/Include/Library/IpmiCommandLib.h
  IpmiFeaturePkg/IpmiFeaturePkg.dec
  IpmiFeaturePkg/IpmiFru/IpmiFru.inf
  IpmiFeaturePkg/Library/IpmiCommandLib/IpmiCommandLibNetFnApp.c
  IpmiFeaturePkg/Library/IpmiCommandLib/IpmiCommandLibNetFnChassis.c
  IpmiFeaturePkg/Library/IpmiCommandLib/IpmiCommandLibNetFnTransport.c
  IpmiFeaturePkg/Library/IpmiWatchdogLib/IpmiWatchdogLib.inf
  IpmiFeaturePkg/SolStatus/SolStatus.inf
  IpmiFeaturePkg/Test/FunctionalTest/IpmiShellTest/IpmiShellTest.inf
Labels: impact:breaking-change
