Repository microsoft/mu_feature_ipmi, pull requests merged in 2023-03, with the labels that each got.

#85 Add Ipmi Sensor commands Set Threshold and Get Threshold.
  IpmiFeaturePkg/Include/Library/IpmiCommandLib.h
  IpmiFeaturePkg/Library/IpmiCommandLib/IpmiCommandLib.inf
  IpmiFeaturePkg/Library/IpmiCommandLib/IpmiCommandLibNetFnSensor.c
Labels: type:enhancement, complexity:easy

#90 Add CodeQL Stuart parameter to this repo
  .pytool/CISettings.py
Labels: impact:non-functional

#91 IpmiFeaturePkg/GenericIpmi: Move parameter validation
  IpmiFeaturePkg/GenericIpmi/Common/GenericIpmi.c
Labels: type:bug

#92 IpmiFeaturePkg/GenericIpmi: Fix CodeQL type comparison issue
  IpmiFeaturePkg/GenericIpmi/Common/IpmiInitialize.c
Labels: impact:non-functional
