Repository microsoft/mu_feature_ipmi, pull requests merged in 2024-01, with the labels that each got.

#200 Add BmcAcpiSwChildPolicyProtocol and RedirFruProtocol definition
  IpmiFeaturePkg/Include/Protocol/BmcAcpiSwChildPolicy.h
  IpmiFeaturePkg/Include/Protocol/GenericElog.h
  IpmiFeaturePkg/Include/Protocol/RedirFru.h
  IpmiFeaturePkg/IpmiFeaturePkg.dec
Labels: impact:non-functional

#201 .git-blame-ignore-revs: Ignore Line Ending and Uncrustify only commits
  .git-blame-ignore-revs
Labels: impact:non-functional, semver:patch

#209 Update pip-requirements.txt
  pip-requirements.txt
Labels: type:dependencies, impact:non-functional
